---
- hosts: local
- name: Create EC2 instances
  ec2:
    key_name: jenkins
    region: us-east-1b
    instance_type: t2.micro
    vpc_subnet_id: subnet-109faf2e
    wait: yes
    exact_count: 1
    assign_public_ip: yes
  