---
- hosts: localhost
  connection: local
  tasks:
  - name: launching ec2
    ec2:
      key_name: jenkins
      instance_type: t2.micro
      image: ami-08f3d892de259504d
      region: us-east-2b
      wait: yes
      count: 3
      vpc_subnet_id: subnet-109faf2e
      assign_public_ip: yes
  